security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login  

    firewalls:
        main:
            pattern: ^/  
            stateless: false
            form_login:
                login_path: app_login       
                check_path: app_login       
                enable_csrf: true            
                success_handler: App\Security\CustomAuthenticationSuccessHandler
                default_target_path: null
                always_use_default_target_path: false 
                failure_path: app_login
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_logout             
                target: app_login            
            remember_me:
                secret: '%kernel.secret%'    
                lifetime: 604800             
                path: /                      

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_BOUTIQUIER }